# Generated by Django 3.2.5 on 2021-07-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_orderlineitem_room_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='room_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
